CREATE TABLE STUDENT(
    NUM NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    KOR NUMBER(3),
    ENG NUMBER(3),
    MATH NUMBER(3)
);

CREATE SEQUENCE STUSEQ
INCREMENT BY 1
START WITH 100;

SELECT * FROM STUDENT;